buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
    }
}

apply plugin: 'com.github.johnrengelman.shadow'

// Apply the java plugin to add support for Java
apply plugin: 'java'


// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

configurations {
    sparkCompile
}

dependencies {
    compileOnly 'org.apache.spark:spark-core_2.11:2.2.0'
    compileOnly 'org.apache.spark:spark-mllib_2.11:2.2.0'
    compileOnly 'org.apache.hadoop:hadoop-client:2.7.2'
    compile 'com.beust:jcommander:1.72'
    compile group: 'edu.stanford.nlp', name: 'stanford-corenlp', version: '3.7.0'
    runtime group: 'edu.stanford.nlp', name: 'stanford-corenlp', version: '3.7.0', classifier: 'models-english'
}

// This line is a bit counterintuitive: we are adding to the runtime configuration
// the dependencies of the compileOnly configurations.
// The reason is that by doing so we can exclude spark and hadoop from
// the fat jar, but still have them in the local classpath should we run
// some code from the IDE.
configurations.runtime.extendsFrom configurations.compileOnly

shadowJar {
    zip64 true
    configurations = [project.configurations.compile] // Exclude runtime-only path
}

