buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
    }
}

apply plugin: 'com.github.johnrengelman.shadow'

// Apply the java plugin to add support for Java
apply plugin: 'java'


// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

dependencies {
    compile 'org.apache.spark:spark-core_2.11:2.2.0'
    compile 'org.apache.spark:spark-mllib_2.11:2.2.0'
    compile 'org.apache.hadoop:hadoop-client:2.7.2'
    compile 'com.beust:jcommander:1.72'
    compile group: 'edu.stanford.nlp', name: 'stanford-corenlp', version: '3.7.0'
    runtime group: 'edu.stanford.nlp', name: 'stanford-corenlp', version: '3.7.0', classifier: 'models-english'
}

shadowJar {
    zip64 true
    configurations = [project.configurations.compile] // Exclude runtime-only path (which contains the models)
}

