- hosts: frontend

  vars:
    java_home: /usr/lib/jvm/java-8-oracle
    hadoop_home: /opt/hadoop
    hdfs_volume: /dev/vdb
    hdfs_volume_mount_point: /var/hdfs
    hdfs: {
      host: frontend,
      port: 9000,
      name_dir: [/var/hdfs/names],
      data_dir: [/var/hdfs/data],
      replication: 1
    }

  tasks:

    - name: create hadoop group
      group:
        name: hadoop
        state: present

    - name: create hadoop user
      user:
        name: hadoop
        group: hadoop
        state: present
        createhome: no
        system: yes

    - name: format the volume, if needed
      filesystem:
        fstype: ext4
        dev: "{{ hdfs_volume }}"
      when: ansible_hostname == "frontend"

    - name: make the mount point
      file: 
        name: /var/hdfs
        state: directory
        owner: hadoop
        group: hadoop
        recurse: yes
      when: ansible_hostname == "frontend"        
      
    - name: mount the volume
      mount:
        src: "{{ hdfs_volume }}"
        path: "{{ hdfs_volume_mount_point }}"
        state: mounted
        fstype: ext4        
      when: ansible_hostname == "frontend"        

    - name: copy configuration templates
      template:
        src: "templates/{{ item }}.j2"
        dest: "{{ hadoop_home }}/etc/hadoop/{{ item }}"
      with_items:
        - hdfs-site.xml
        - core-site.xml
        - datanodes

    - name: copy systemd scripts
      copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
        - hdfs-datanode.service
        - hdfs-namenode.service
        - hdfs-secondary-namenode.service

    - name: enable and start systemd services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      when: ansible_hostname == "frontend"
      with_items:
        - hdfs-datanode
        - hdfs-namenode
        - hdfs-secondary-namenode
