---
- hosts: all
  tasks:

    - name: make local directories
      file:
        path: /var/spark/local
        state: directory
        group: spark
        mode: o+w
    
    - name: configure spark
      template:
        src: templates/spark-env.sh.j2
        dest: /opt/spark/conf/spark-env.sh

    - name: configure spark defaults
      copy:
        src: files/spark-defaults.conf
        dest: /opt/spark/conf/spark-defaults.conf

    - name: copy systemd scripts
      copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
        - spark-history-server.service
      when: ansible_hostname == "frontend"      

    - name: enable and start systemd services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      when: ansible_hostname == "frontend"
      with_items:
        - spark-history-server