---
- hosts: all
  tasks:

    - name: install start-spark.sh script
      copy:
        src: start-spark.sh
        dest: /usr/sbin/start-spark.sh
        mode: u=rw,g=rx,o=r
        owner: root
        group: spark

    - name: add spark binaries to the path
      copy:
        src: spark-path.sh
        dest: /etc/profile.d/spark-path.sh