---
- hosts: all

  vars:
    spark_volume: /dev/vdb
    spark_volume_mount_point: /var/spark
    
  tasks:

    - name: format the volume, if needed
      filesystem:
        fstype: ext4
        dev: "{{ spark_volume }}"
      when: ansible_hostname != "frontend"

    - name: make the mount point
      file: 
        name: "{{ spark_volume_mount_point }}"
        state: directory
        owner: hadoop
        group: hadoop
        recurse: yes
      when: ansible_hostname != "frontend"        
      
    - name: mount the volume
      mount:
        src: "{{ spark_volume }}"
        path: "{{ spark_volume_mount_point }}"
        state: mounted
        fstype: ext4        
      when: ansible_hostname != "frontend"

    - name: make local directories
      file:
        path: /var/spark/local
        state: directory
        group: spark
        owner: hadoop
        mode: 777
      when: ansible_hostname != "frontend"        
    
    - name: configure spark
      template:
        src: templates/spark-env.sh.j2
        dest: /opt/spark/conf/spark-env.sh

    - name: configure spark defaults
      copy:
        src: files/spark-defaults.conf
        dest: /opt/spark/conf/spark-defaults.conf

    - name: copy systemd scripts
      copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
        - spark-history-server.service
      when: ansible_hostname == "frontend"      

    - name: enable and start systemd services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      when: ansible_hostname == "frontend"
      with_items:
        - spark-history-server