admins:
  - name: ceccarel
    password: $6$v1sQ32TdgOrrd3$F630Is2SRna0mp.M5iKZmZaYqS42fon8G051LRIrAxCCvfMcrmw9qva2mhHIu5H1Me4xIsOlcSbzNqVwpaRbg.

  - name: andrea
    password: $6$4C/PRuRTFdIm0HIk$DjmJaN/G6iZ3bjsTY1O4TgZIHBtoYbX6AJPZUaEa6Fg71HpqukLEdSiIHFG/Ti1oW2znBAJCeO3EmrkhqzjiG1

groupusers:
  - name: group01
    password: $6$0.kzc7dQkf9t1anW$ldJkkxEfKXqFAniFr239OOiY63qHjp4V46fzdft4muR1QHi/Ceczk8CMsIn9bTbrNnKNfs1Tlc6NkO7s3dvGG/
  - name: group02
    password: $6$hYe9.VJCZei2w/KT$7JajyzrNuj7CPTAXah5GhSk3kCp2y0s..144HpX9nuTuhxCHF3oBhnbL9za0HGVmOGbGCdxD4jT9UhcK85MNG.
  - name: group03
    password: $6$99pGSA.DyM8zgBx2$6TiQnTq0zAf7REFDZpo3C0YiZBckPxyCk.WnYYLFGDOJ7RGC/COsD5uqJc1U1sTiyUZl6HbCU6k6O0JP3zZJc/
  - name: group04
    password: $6$KjE3GhOJg83E3X8G$Y/WQV0LX0Ig9MLcoy/bOF2UaETJCDLGq6Hz3IfoqLbomlPe3tvx/zpvfD4.a6VMVC6TkgBjwzyT.axqbeuIUg0
  - name: group05
    password: $6$1efCtpmICwU5TEwL$hbJvTyilxjrQixn8LqM0qitQVLfiVlYy4YAPcYJtPg5Flodi6X7rvCrtLeVVFh0bLqMbFwbaA4Rs6ZUPnElQb.
  - name: group06
    password: $6$cdc01krKJJzWvGvX$0wy9frtOMQvEWQsF8eYRmhisBfYb.gmBY5aJCfrjIu3Nz8ViVcEvN8/Vu7OcYGDAYVS73I9XgwnN/JAivsmJD1
  - name: group07
    password: $6$oe.zAWp5vfWV4v9i$VVq1yXbrxJkhcAbtFZq.FIvjUAOpUS6FaFDl46LnykoRtKc66ajtKUk4kpatqs0WHWEjygFciudvcu90HdSgt/
  - name: group08
    password: $6$vklHPjEjvEe5pQ94$1MBD1UfDLNeNrzt.u6OFgUWVGDcX6v6n6hq..2.9A/G45t.7Zb64LfjRntD6YuxMGYnuVoaWOTwBbp7Jk2XUl/
  - name: group09
    password: $6$05Vn2eMtjg3WxX1l$LizLJCEwre0XgcXCgRbEDDH0KnPmNeXUlNWNm3pk9tDi4ENXZMrxO5R3x7hnKb5Kf6oda7/D290r2jEOfA2Q1.
  - name: group10
    password: $6$YJX7rLn5IPg34OgR$FS/cl0u0OgVEc0oghNQBmW9frBm0ue5Nu/6eyD5P0yWbZkkO9dNyTV9bMQ2LXVT1qUY.uUR2dkvRzavuexH.p1
  - name: group11
    password: $6$h/kjgy2BMhJm/tQ8$auejshc6u9/JSHEF0K9SV2Qh7vQyangfsQyueXD/mneDyg1KCqWJGpIYzbdrr4uWcqrfJinZ2BDHJ2A.1plx20
  - name: group12
    password: $6$PPnyp57fO3Qv58o1$9Hj.f2B//U437BLQDdUWM8CpJDC9Ym.T3MWX6qCHyM.ZGw6/FQM9z24ZJwuIfUjTtX50vZJ5RvGfUtJwoC7vP1
  - name: group13
    password: $6$BvNBUOY9QeJey50d$6/dvUIZfZS0I337q9op.2iK4Q43cvl7nXBinPO38vua9VjbUp1lgzeEM5xtmxYJcYrB5/0nDKAh8/03Kq/Mcv0
  - name: group14
    password: $6$k48BFiBwyRIouKHi$FLji5.RyynYbWyjDGrVQ5itWolsMJSdXLDyXTa66J.XG0rHV0NccEvaAYvtj5OvwdY2qHmKC/QTav3jqEOQNw/
  - name: group15
    password: $6$moOkATclk0Fvk7rv$ybK2sYPZjbSPkAsmb7XRn/TsT3kjgjEaDRo1lH0rtvf1HkLmkaKWSxNfBx2fJ4qqTf4BmaSxxqfdWdXTLaqqD0
  - name: group16
    password: $6$P29DpgNMX.cmekY5$SpjWA2mBdxE0wHrno2.MqWxOChfkXK00JxPH64q56IDjJcTiYpHhUQZTWsYhgQ8L2.WvU.YeX3LSv/rPrCFZd0
  - name: group17
    password: $6$4eeFE8ZEe7L.t7V5$8DjI4jcgn082QlbUf2DHDtgm469h236itPk3BmSNkZQQJSB/K.6A98y8fise83JsZ2Z8HkZI/3NrlLFwNEE.g.
  - name: group18
    password: $6$z2vVkT1Adkyf84Tm$CHFBUfg4m7BiMkcABGD/oDbJo8qgl.sGQWRK6aT28i0X.FyiwQEmwjX8HoGGpkovYuHxWG2wHqVmKWEq6xrnJ0
  - name: group19
    password: $6$sl1leyNTBTI9hhkv$9TSq16h5dyyhGRMU/dMaSIJ4tDQwWkettbXqT4G8ig5C4dxrB.Oz1kFg42.DHnG2WR47c0oUXnkn/ZY0utpb20
  - name: group20
    password: $6$yxbHTH73HiUoRicZ$CJispFgFS86l9BEBlTry0JcqFng2v97ntzQfZt.Mf8Zfs81VbxzZGEpiaiLdTRnWLGyIZNucjnZe2xKRJyzRe0
  - name: group21
    password: $6$BD9xJ6yxb6dSwUgj$SolTg9RYHXuOb6dcy/epZmZZQpFtuJMY4YSjl3cVgKINt3t0ph9X3bro7K89XsciEP/Yeq/S2907twno7atQj0
  - name: group22
    password: $6$oelcsTw3l3NfrdGV$sw1qzkZsUogpXGquyJYVuc96YwKMAPPIXH8CWhPX5PoOBmUsTnYfBiu/iPT0zziKIwrdLrp4/Vql.mzdKC9Pp1
  - name: group23
    password: $6$oLnVfdD/UDJ3hjiX$nmMSlTXgy9A3lDYyzx9gBkthxZmHT0O9UkFLPywGumbfTMcg4JX/3rV/eA0ye8tMc.15uStMPN1pVLkXYhWFt1
  - name: group24
    password: $6$m5D8jlczCULv5SG.$cvHq8vxtQKEctXZLd.X.w.TunqILKXKlZOZ.OwYgaxnAhG60x6R18/IpuPnCnooy6ycA1da7hYxhTwap/5FgI1
  - name: group25
    password: $6$zonm6ZgrTght8NRm$bRMSk.Rhi7.tZCM9pNeGS27FgSyG3cEovZjnO2gVA4RgxHw98xGMo6o/pzWrZNnoHuEOPbb7Zp.cNm5Szk8E8/
  - name: group26
    password: $6$xNS6Rkvz9QAVRasU$QCnlAOEktbVE8cNcsUQsOOagjNr5ooK68XVS4ePmL5SUQKPDk8s3t6oawU6nHilPiMEj0P6oPxWwHQRxELieY1
  - name: group27
    password: $6$.328VfMqzLsUBuUZ$pT9uCFMlyphhiGOYop4K7TpHa6F3HY/dvwFL24DWnAnxokzwpbPoUMzTmbMQDTllZuuFIwEyZsmUGpwhuU5/q.
  - name: group28
    password: $6$7saBFs4t5kzklFr0$aDhtr5ezSL.2VvQ9C812fJqqciQcyJoB6t67ML2ETH5kALbcYUFNBS2i9BKVlEAe/8DAeVR.89By04bFTTms8/
  - name: group29
    password: $6$i6h2Kj85Pb2rzHHp$a1zHuRc6rsZzeEDzlztqLPDxMjGz4FeAsKFd2YXUucHfnsydrBNt03yVMcM4JeJH0rAGWsQNIA0a5IyyBC0wN.
  - name: group30
    password: $6$l3fPBmHF/H4c5zsw$O2JxocwEeX5Dun6KQwKkQMBRfYhSFN.jvWGotekODcBbET8grcgxYdwjw2KPxKOvJSb.wa14PXLPjFpL4v6Kh.
  - name: group31
    password: $6$9s8zRDDOixTURePv$YdCMMQXdDU.wJsSikj7QC8WnmSBwCWYed7j2UjAlSotccNIRcEy2FPGWJ7cgLqtWozfFIlKpVPLV5MzDvErhx/
  - name: group32
    password: $6$Upmu1ZOrOsA9CXzD$uIgkWPYPCMxxryI6CJ/0dZN2NbGECWvvw0k.G4/seB/B7quaOMeujyJQmk7AxhAFPtofctccfSDLclXvPZHwg.
  - name: group33
    password: $6$Rh7vWW9NSIq0DZho$ExuuT6tFYYnRIf4rgNjVk/c5s2ZxZTepg7fum1uvOXkKN4baT1udZeTO9Xlrvk7JmXoZvldCBNEf.CKRF0nej/
  - name: group34
    password: $6$xXX0fphwRdpdywCO$NQLMCGAMtIJaqVQDCDPu/g8LOMxAhO1WtxJNn/HNQWaG25PkcrQL3s1w3mrRUvshfpa/CfqpNzjc4.8.UzAFW0
  - name: group35
    password: $6$UDoUuAPrnkigSnk5$7oq1ORIGlDHyO33WnVCMEUfQLiwwZjWg4qF1VcIsgIPOF19U/p/WY3Hwp2i/O499Ep9mTvPtpjy8kONgXZbrs1
  - name: group36
    password: $6$qDy1JyPN3iE7zjYn$ZwFCNF3SrBfwB3mDKWfrmoQxGooYzs68p4Y3ysmAtwMR3jF2fKXsdQFC6z0Hdk21wJkca4oRSjEJrLEyNaLGt1
  - name: group37
    password: $6$GaEsieIpHYo4afV6$Dkg9OtR2q77gbjY2e/nfQcCQ7Jk/q6yBdYY3mSTA84jNlYsR.2bx5Iw32yTZPBK9GR5diyoW90rPXQVl8.BUW.
  - name: group38
    password: $6$ceONMbvnVU6R5JMB$kPys0Ed0GMoY83Q4jKinMQmNudcNrvgWEYAijYWkXmEuJKhoXBFUJwhuv9BrB/FyHYbrYxW.yqczmjTVYlEHK/
  - name: group39
    password: $6$N7.ApERelASw2afI$PGg3Kciqob1VCSdhTt3dZnrX2we.modupUPPXXbhe000TQlodkhrW3PhKEv/eKVnWU.Ab6dxz.qko7VNyXAlV1
  - name: group40
    password: $6$mNtNRlG7Bx0Ecy/2$MX5XcXixXCxRlsxRReJILyuBjvnqI7.7UvV1c6W7x91hKSw7ATrpGgXG/r69EpOSBzvemuiKlt00.2xLk5doW0

  - name: group01
    password: $6$eI9VoitW3f/9atNR$DH5WfXg4vAL0VW9FO0lif7eSSxf89i8ITQSe7o/8VCfqGX81vmv/2YNVOAGBlE/C1IaKmkoM8LdwfSFeWxW2z0
  - name: group02
    password: $6$jeNLBi5l/crdClN/$9FsvDSLpon0alJz0kI.jg6r09Eou6oWPEdoRRJiGvbRAfyu7qHujLI0y06/KZLDi3mLe0ddbwhe20nUPxaU.l0
  - name: group03
    password: $6$nnvJl0X2zZzmRShe$XV5IIL1GeN3FRBJQM51iI9aRECow4Iu0r54syIfwGHs2ZSLbe9v/gk2dUu2a7FMd32n3nS0U.BRfKcSL2gjTa1
  - name: group04
    password: $6$fk8dJoOY1.k4dLl0$Lh3rMTWTiUX31GL55EsHhCMlDNHhqF0ChXNhTURc.k.bOWXo.O5qx9em.p3DQwhlgAZIt3sptygMSHqEF8UB4/
  - name: group05
    password: $6$EzEauPWVTclMunWJ$zDoF5ir7rErqpNnSN1GfpmaSoH7Qeigvu46XNL1fMGYbeVxmbBvSczrZTlEwr9sZFXlIsU7wuJCKZhvUCc68L0
  - name: group06
    password: $6$/OgcrZGfebTP40np$3f7THjUtw2a.a1KOOqhB4qOaKdk9NrubcFbTQLHzK8tt.LN78vp9cRrm642ku5Giy8V/pvRAgCAMRbuSNG0gj.
  - name: group07
    password: $6$895ni9WAMrWXIPIz$toiBwBozQBGCuo.QOLfnZ6JxgX0mBdyx9YSgZ2bR0JahI6KFIdarE4srKBEfJxjiHgoxn9cWB/h6TlMd3JG4Q.
  - name: group08
    password: $6$pJxxtYo0W6OKF5Ed$mslr3cow3PU2hKYDaXWefeeWXmgHY4Mj5tPq8w46EIrVLguo.wRSIpbzaKkYrglOjYUPkKuRh4g1OZ5Mu.LXw.
  - name: group09
    password: $6$NKv3EvZzQVJueRbe$447VjHvRo3LMyzFLUqpAXqrRF1nH1y/th65/f39hYQLAv9GFp8Ht3a6I/yW0/J07wC89EV4tAgL.9B5fO0Xco.
  - name: group10
    password: $6$kDBzsYE57sv00MnN$PYBQycKojXsIohL9EqhZ0wwr1liCgfT0eT.0uhfooFqYoq8tSycJrhE/sykWt/9RwNBi4EIq2hWaLTw0N.QyH1
  - name: group11
    password: $6$lN1Zvd69rszovjTT$qSqCPe1qUazhNYmpXdkPJ1zfczJAhMhDwThFl1DwzKRUKjks9c0YhpMEzy/WGHndICknMcpEPTdv7veCDx7eE1
  - name: group12
    password: $6$YZTPeRRvdvWL0RVu$j6RudIOBui.KmsdYW8.LrolJSHacxUbt8etjnGwMZZtUxdi1RcCj7.5gQ5eUPjnGKVxjjO3Svn4eVpTRiFzkU1
  - name: group13
    password: $6$/CNM08MdxKootpul$avfsZCH9UUUmcKaKiR2eHRcERiqHwkBFxrmqCl6Hwo6nsv3nVr9wtmr1HtKLnpJfAs53J5LjO2Il6NjJjC7Fd1
  - name: group14
    password: $6$iX24G3cs4hdWgJli$jRRXljUXO0D1JaS31wmIwIFH/aYw5bTJH5ao1gqLlXyBmo7WchuCKm/0uVBdLKun2xK1/CZXdiyyU/dqpdU3Z.
  - name: group15
    password: $6$ZGWSfacxW5mvcbiJ$VqMf2RqyCubclgTw53RjL8UlqXDDA/3bmb5FXtH5iVMcwTY7JrSnAxUUwpVYX1dMgHHgFrVqhmYlKJ3NQ8/Au1
  - name: group16
    password: $6$gGLioqtBEXzb/SMJ$JwsR5c/dNuS27o1gyiaNOxBLV74fwiXVaMMVex5cg.1l5ErqjPLRWGfpmJxdu3BU.Hv4QH6kanMX9gK3URkgn1
  - name: group17
    password: $6$RYaakMYqve3OH6rU$rCV7kJFcZV0xLkPvfLy2KaPQXD6pt9bpM0mwuffME8.2JOk8ZwA/ZtQqEFOIfFbglDRX3BX5VlPwZIMVfGt/M.
  - name: group18
    password: $6$ppQ3yzeChrdslfC8$ph/nCXiqCRDiRgVkaWoObqLbGbc59koVq1gCz47/PLkY7WEwgFB78kX.XstzgZwOUy0U4DskOpt9lTyoRn4cv/
  - name: group19
    password: $6$bseZTmybNK9ZV9CE$tvWKfSVp0K5y7sCQEVxcBnLs0E2zPibif14/sodu1oUTp/.lr94UUWKOtTLDkCbi7/.v0FqgeObtkWaIK2Vhf/
  - name: group20
    password: $6$49OqPW0qwmeFlcgo$TmD2RsFe3HiSwdMqbQKYeP260aMWsgX0GEWU8MXsL7Qtg7PbtC1hZhDS4WRAUcnuAu0fHMR07NWGuM6HO9OTk/
  - name: group21
    password: $6$.XdmutO/dIqH0tox$EsNQ./51knNVd0MlFQera4IqPlV27sYEGCMEoc0p/juycAyenFcd17Nwxf8aXrpp6IxAZ1GBVT7oBYT3CZw/U0
  - name: group22
    password: $6$ynuHdIslPFMCt6uO$kUgKKMz5SI.38sftGBAj7A.4NLSyxaAWZhc/NchIBmQKMvwYYTrPEbRaBzDmbu43u3cuyvg0UoJjRs8k2VGOe1
  - name: group23
    password: $6$dgxc0pDz6A5pyVE0$ffPj2kBVMt8mz0r7v7Sn1klPXISf/27Wt7wgaBKkMKeDKUKbaBCoj7Rlbae6Ar1VH4xDh.vKhjF4sfro1qkaF.
  - name: group24
    password: $6$Jj.2.J3gw9iLWGnd$5RDhaA8IoZj2dXNYvp70O/POq33XsX0PDxnqB0aIl5RsgTlJ3BNCNxNCqGjyE/Z6Ovf.x9pIyZs7CCXm4GOvD.
  - name: group25
    password: $6$I1y/KtNff5OapAhZ$eCczi48mCU1pQ7jvw7HPU23JIzZyofnUOzLEMvRXbDhgcuckhjnBaVrB57rRzwWS/XLm7it7QpoWP2ng04tB1.
  - name: group26
    password: $6$SnrJNG4ZLIsGYgOa$LcI0odSpRlLi3.nHuNa/QSwu5HjGNjVFCRFX8/0ZHUNlQdEPfccaE5By0KuUM5LG9S7fL2sb170Wivl80rjLx0
  - name: group27
    password: $6$y0OEsGGFt651Z7jl$nJjMWAEv6bLyA2iHRrmBJTLYO8S4F41z4F54B.EkXXWHlsfu4Z/7LtEhZ8m36BSXIsfz.U.c/KHoAzEDANbNk/
  - name: group28
    password: $6$2IWZ5zqZJ4pVZAK4$zuEt02P7dPknCLbKd3d.IbFXbURSVDpV/7Mjsp9swncBQEWQgx3JmjaOJF/lAcIsyPj.7YMbCpm2NP1vP1m8z0
  - name: group29
    password: $6$ucQ89RgTjNg11T1G$7c5UKBk.zm2EiNr7dyg8ZFOr9e2rz7yFMEBXe4Dp5846nTmtHAeoT7OrDTrcuYa7585MOg61zAzYqWh30F8kG1
  - name: group30
    password: $6$U2wfkX17SOkq5eAd$UYayixx6TlbGsy5IkJGusxEHYAS/TxThv/rYUbcAPJrChT.eo7x/N.GhTwT5RFC6iz/m8zChBQpUv/BjG.kVQ/
  - name: group31
    password: $6$FxkM0AJajL1lFnwM$FaRDAbhMSvbq6i6yVoldGLGP3BlE75pUVa10Rn/BvM1NTbNa9x0GaVzgAIpU9w5cmy9Ww0sX710KxmbqTNN/o1
  - name: group32
    password: $6$BHgC7sQJS1MDWr0b$lUJvOT3.AVT78XzikIaQWK4Pz44WS3XRnn0luoQdYRLyBFt.csrmyLCnkJ8rtS.yWakfuuSA4nqF9P78ED3Xu.
  - name: group33
    password: $6$25LTVcfiWVAUqXzg$UxszvZ55CWR7lSFSKD0vqY6bBi3FN9ddkGyha0boTBaWLBYknM8y/OX6fvnvkz8LDCCHnrMijE1gFttsoneAf1
  - name: group34
    password: $6$paVKXzJanJKsv4x.$yDzXFQhlwJMn6kxFd4UV0ITYHcInujHVdcM0TWgW2YSBMuu8meREdseebWCFSYK0u9EFSoLsSFXI8XFzUiRGo0
  - name: group35
    password: $6$2zsNNpgEoN7vtQMu$MlmLy/8mEnUbXIp8SVWo8qieFa7UiM.f20fIOCqyFLe5zaAHI5VvF4CjRObdBp/f.Nah7n8bz.VOb9buqFsa30
  - name: group36
    password: $6$gRk1ZUBP.e5ujQ11$iVeBeVaPgd5YHnTdD8A8Td8jSZv7pBIyt/Jd8WogFiERjT/F0614WhuzYaVlD4ARGlVRmW/ocifYR58NyK3Br.
  - name: group37
    password: $6$lIQ2DuiVgKnWndC1$qTjo5n8xBb6TkDMt84BP1pJrT3ADfAUL6G9OKsaUR5TZwNgDnULGov31oL.gcT0REcBfqsp69BT6dLkvZFss5.
  - name: group38
    password: $6$I0McSlDsU3wP/dl3$kfsR79YPRk5fbXD3U.riUgZUXCN2hJBPITn6hJk5IkwDR1PDtx8l0J4zrmGtKL97O3j1RMGo6kyNebOWRGKI30
  - name: group39
    password: $6$5ScebQ2YM4T4UwBi$6uoJaFdafJqvOlICwWgI2j47l6bg/W3.A9eVar7s/90HEPgbFLBNswL5LKos7nhVSshC8FWT.jA1mbZDGLkR0/
  - name: group40
    password: $6$cKCKRJFeeQkxOTjF$emxLSJIku.qUqCesof.hTkbZ5gb8hf6ufB0oyDHJu/PFmFGvzEbor2GltuJbX8Y2gYO7PokNeVyfoceKtZL9G/
  - name: group41
    password: $6$20rPWKRkT07jkddD$jMTMhXFxvsGBYNfCqHufCRwJU.Svlzi5SryH48pScKyaWYjQfqzmQsb0vxyOSPTvatMXI45sOEK5fKTOXtVdT/
  - name: group42
    password: $6$OyGGWh.olBvAsGSp$MgJKkXQ5cmOEYzWHj.vUpoaZgW671Z7SJTZClDia0WpGkJ8JWU3Ls/hNFtRBOQQcqiQjHCpDLlQbEXaDR8xWQ.
  - name: group43
    password: $6$4InWmz67ZnkgComk$XWrsMGomvR/buy86/vdr.EAPA6W8EJsNBO8/1iCpKyQefYZyh79Ok7/dEd3MCUqJnJpFm69.72gKnKrsgVhQq0
  - name: group44
    password: $6$oQ.CYrYZ.ozFe3YJ$aGQrmELaALfEiZ1evWS6l41c2yYzRXDGK/feqfx3.mwxntCaRYDb5gI4WhZD9vsDTTtsFpY1oqzqAOJIzYZbd.
  - name: group45
    password: $6$Y2.sO50AkZpnVXrr$XP9CBLniq1jrGEfal69uip1Xs4Nyh7Rl70ZCwYtv.bKz3TNJ6xzC0lBeb0XDu3FxgLnBAmyndhQncjQ2/u/Es/
  - name: group46
    password: $6$/HOjObiVI76pyFbN$3zJRGOxSKgqgaLJ6Uiji5k87YuXO1yFApbwEyuStpVMKLVNWKQrUpRpf2YKo/1rPFn236xM5Z8dxUd6ljhAq//
  - name: group47
    password: $6$w.yUyR11fYWyYT4a$r5dkqr29.dd2JuJwIniKLR0WvQ5B3GA4EVUFVzUeWobjaYbD.lXp03YIVOwTEMzTIsdqCwLEB/kaJRQYfUr1x/
  - name: group48
    password: $6$bJUGlN1wF7j09AaL$MUkkqm95CTRIbcCRXqbHXo9LOhiwKDO0xwy3/BlD15DQ9kGu2WmBUnH4mqt00aiH6p3QPY5/C3wMJAvGvTHAs/
  - name: group49
    password: $6$ilKpuUEo/cjkJBy2$VPGYB9cdOU5C8goOnasuF.pwhDZXkZRPsktUSkw.GTTquOzpX4.qUGrFPJ4XGuH7b8FqkBa2Wi6n/sCQ09wJS0
  - name: group50
    password: $6$zu2/hbCC0HgPvrCQ$5pjmX2yuVYFW6v4z0QyW9NUYy/CnJ.Z9.8gFala7Vki11jzp7bsq4wErx9kiLJflBbahJiwN1Zyt9JdAluxfq1
  - name: group51
    password: $6$gFjD3ath.mVt450y$VI01Kc9Bq2JvhsF1YPbcGMJIm5kX9psArNqfmeKQ2yRKWZwE4rWCF/jEqNjrITH8QCCiIZ0tY1r9./kF6h0xw/
  - name: group52
    password: $6$qahDFVGsy6VgpI/3$27g/HvtRj6ok.tuB6FFyInVnE295x.3gq7sZO7PrgZMEy1ijwdMYyvqhq3ehKDMt8kBB5jvdDRHBZe3sHajuY.
  - name: group53
    password: $6$zM5464p41HqEoZoM$2CvGjmKzecx4J512N0MTvoIGVlXdtGWXyKDuTt28KjaO72prfmfx6mn96Dy3yCmJooBqmgiLQc9zpO9fR3G0g/
  - name: group54
    password: $6$3wv2.kBfx1WzaMqm$N4r3Y3cMOxMx3VCCsfsmDLlxMe5xtN9ivptKxSBcgLBisIGrhfFteFgo3pDlo5SeIgvaEPjJdqTZOjRpzPRK1/
  - name: group55
    password: $6$h7.eoMKZYIIzieSj$9zLcuBdREmKEBZ2JuZ8Zc2c8S0LZ.Vk6XYtMJG5n2Utu0jO.qlN38/NW/8ZJR2w1TG9l4zcNiBQH/y388sQue0
  - name: group56
    password: $6$437EzsYI0xdrYrRe$7uhy2ghsHss6czUp5MPruueqFCkEcvn/1LhgzUJimxgC7S0K3PGfRUu.HJKam/vV1ZdszzcUgpBCmoo.aSsc.0
  - name: group57
    password: $6$3O7ZWwhRBxK1SzwN$byq.qqFtfXrmDB2u.yW1LNp6rZ5a5U1WA3deYutDPG9F8qX7mtePzzKXsZDpeOPxW1f0Uv2.Ztm/MX6hZDPi9.
  - name: group58
    password: $6$V05403eASaXNkSWu$zzbbtv2fFcUmjQBi.uqUU74/SB5tZ7dWweSv6Z9kUPB9PSn3hIF33MMcbS91k9VaY2fkF.HUvhGiLLzEIOsre0
  - name: group59
    password: $6$jFtPrb51MY2KsjO3$V2X8G4//oQTTZM2LdyXbY8N300YDKvARKdgPpCG8vo3fDjiNat6nqxnm0UDzT.jfi9l0uS5cT2Uiol2JhA2Dw/
  - name: group60
    password: $6$zGk1Jlct3b9j64rf$yrAwe2X2.wwvAiAktLLKdQaPOmEDJYRPrF7JFSZORfbF9G6gh2cmSnsjKG6vSWX0hZUrPcrX4x99tfJWw1B9k.
  - name: group61
    password: $6$ZEZ/hNZlbk3UVgqF$CvO9sVPohMj7srve/YYqsn1GUn0KUDrm1iGB0izAbHZWpR7ZjAAEq991TX0iUIkPG8Wln2VT60Ihk/2CIUH7G.
  - name: group62
    password: $6$LhN69HUPyGC4I6GA$odjCsHGgxzKQ6b80MDVTp90JUyPpEJjCLFVMFMvM2NksDeYvtAHC8xs9TbssbTSMcNpSrU0Kma0wBcUKk4oRg/
  - name: group63
    password: $6$RMbv8cpButhemk9g$fNIg7UshVXFDBgKb5BKX1ubV8X.Tp67Ti7mgUg5rpRD0BKzFZkF9ecoDFnJ634U.7ueZhAwnS6V0/1apYzonp.
  - name: group64
    password: $6$JcHLHtX8zpxpjohN$CnIkmsW9v8Jf..sNeZG1LYFTWKGJKyjMpKAio5udRT74js3Rl0Nbh7Lxpq3a.dh.9.Iab9MFd3NUFS.io5Bqy.
  - name: group65
    password: $6$OQqkTeqdGvdDWVWC$V1pZm4moqaGdzzJDjUEjsH7m9xTBTZiRZWEIBN75i.TSUvauW0L/RDu/Dk/87r.lLt83qFyYfh9PAVWXpCl/h1
  - name: group66
    password: $6$13RiTHTyHb4Nwv.l$kjFf1Fdups9ejgpC0t41QIsLfJzGBaaq60sWhJyqKxhyBcV5AC6y17WZHUmS/bYT/lIbNOflHwqHZYoq41QNg1
  - name: group67
    password: $6$NyU1bdRSgoPnI7nY$meX1rfpxp0bQ8AqsfbJDtvjj1Uh6nbTHWEDVs88SXyqtwIT.x70mJVDuPq3rQV6EZtfOF5Gwq5oT7aRoyYVfI0
  - name: group68
    password: $6$5KD.vLPShE6VmQJv$vpA7HyciYl0y5v4SHYqgSZycALNaAPm6HU/S9racQHOSSDG1d4AFdFUFYL9aM7w46hx1T2rikP/viGdiakzaZ/
  - name: group69
    password: $6$/nUQgfEJhs52dZT8$tzc.K3hhTtgIVjDieTSV5VZifvAgG0N94bnFBFfdHb5PUCc1wFr5QBkURX.WObt6vQJsw./Nq0SkbsdNn1t6Y.
  - name: group70
    password: $6$Tr3UOji6el20/sVC$CO8qi9ctIrra7mXTJqjkeJd8AZzQ1WUx0sXt1h0rsDDQj2T2wz9I8RAGlCjOdtJYFVGVSj./L2vTmIjIGcB5S/
  - name: group71
    password: $6$xypo7yyDfW5Wj8RV$6prCEVnv7HacdIG4mb4GFUOkyXdXi./fn.ZF1zqgTmu/e99XzdXTpEIHiJPjs6uNMbjCJlmMRVp3UxS/HHp5b1
  - name: group72
    password: $6$5THfxhUfC3tOTukA$dg15kUbwxhm.3nIp.HDOqNmAPtfoOr3xvPm/lJyaVjFeAJK7HsQJpdf76QgR31CJzNAzVwqjxq7X/Yd8iA4pg.
  - name: group73
    password: $6$AGEXvmVzhoaCIDfQ$4pJPqL0iRSHS4/ve18ceXBkhO1PbcBQryukdOzk61Rpbb1/ojN3ST5B/V0Jh/UfYSMdLpTnydrmqPe0ZH.5uo0
  - name: group74
    password: $6$JYuNBHQ0iznsYabf$aS8LfZ1f58.tiGsbIS4ZB1DEG37v95b2TEAPeoa2SIAqCApALJuulfaOJTuSG9Lg5Wjy7uVXhItKEVX80Lpi4.
  - name: group75
    password: $6$OYeXMiV5ZABvs9GV$wA8XB2iyXX4.JVCPQ88JUJ6IwnQYOqpUbO8KeRe7lbhLkWT6jCypAyWQ8OjVvERGz4/SZecir30NkYzPTH9zM.
  - name: group76
    password: $6$IWfrxs0BA21lTVh6$8fJHbyWfuFjmSHFRsTPHB0h2cT0MYM4QKLFkxjQHVPHDbi4x8sleZblfF9icmDbmmvQJFkRlEkSHDEivE1Ngl1
  - name: group77
    password: $6$9bGh/fgdKVqRgLnP$2pgXFtiidML1TQoKp8wHL2mqGI3lw9xF3sJbiRauJQV986CVpkV3We3ZsWNQtqrbjEN9UnqLKdvNjPS4Q7Afd.
  - name: group78
    password: $6$HsTA/UgDGzM4zLv/$RerJXQ.xEy3UjoX86X7RoF7PSndyKuRRFKNXhTND.yDN7Y5oJlMi911UdSfPDjnsYgGMdjbY8JFEFYyiwiZ0s1
  - name: group79
    password: $6$5Xvt549Zkyd5CimT$dt/hqJdrZqYzqsMyVaDEizY.FuCP2nF3.B1nIwfaVFA9chWhnw4uTw20q0/NYRYKcKITvt7p8b5K75TOBANTZ0
  - name: group80
    password: $6$aXVSwg4Y1hOTAgC6$RhufjFQNA8vqITGoBwg0rDrpFksdzG2no2N7g56DFyf/zQ2tyVwK8e0YCEMGD9PN5h5QmFD0zoVj6C3ve49i.1
  - name: group81
    password: $6$CR9iwNOZ.OA/GG2L$.fWxgCJZI6lHNB705.fKl9cGkEin7xTRUjwaY4KG5A8yEDuLAv6AaUCgWsxzJOW5zkQqlvVsKTbboIDKgIH7K1
  - name: group82
    password: $6$cI/.stLO/VcAA5fy$n3nNGOoFJl5RwTkfQaZn1ppKCGpCSS.lEr1faaNBKvS4Ch4wEonWgfjdAkm6a8dWjL7/kowegxDNS4az/YASt/
  - name: group83
    password: $6$KBtVWOa2bNSfeFoE$S4riLs8bOKPDJd06Vs2DCrEMSnR1Jn8F4u4z.j8CWhTbXcFp.JPvygRnhChvXxF4S16yx/uqUjW1fBCd1Wr1q.
  - name: group84
    password: $6$f45Ehqag5RvTFy8c$bwDFtVr.n8KQN3t3SjRy6L1jm4jbC/XUQRDPV.Z81jQkZUlc0yoM4Ezn1bBg8RXoc/ofljPi9noRYXuSc9TlX1
  - name: group85
    password: $6$zq.XYz6CY90bA70m$3cMCVjdSTsbt.JJZJ/Id76nRP/rKQ/QcRGoAxzf5xhEzQ9IHspTOwJpypnxSQbvI1z.OzN0PwD.4/DxPrfLm.1
  - name: group86
    password: $6$tPVj7LEmb1bPDLfB$a0/r2SVU/zwPugYEiJmNxy7DyO9FQKXO3V9ayomUoGWefrqGpXu43qoQwgJ7LtsWXN.lyAnIAmH6KC/ntRUAe0
  - name: group87
    password: $6$eJnCQyfzwEFKaUlG$cy1TJJze0YbeOUHG6YB5123nzb0KIyvquh7AHLfhUeENmuLjtjFjgAKskEwtpnXzt.U.vV17t.1JRi42/Y7w11
  - name: group88
    password: $6$3VkcuN7n9ccj7KGo$yDyVzYYfM/QSC4bAZe8b//SP9AMbMpPEoQf7hIf2lVGOoWVfeRWb47x4fWeUB9UhJeWB3grf6b30NtqGIFNeW0
  - name: group89
    password: $6$XI/5f4Oa4t7RDPiN$DR6bqK8j2NW88e4frEOzuXktks6Sdv/d04viiJR2njOngOslDQEOZN6G0kOe6YaxffpwG6iQahKr2/4aQ68Ui0
  - name: group90
    password: $6$EocYUbba5eN.Gdfo$BESPn/XvFV1l3B65MDLNzwrCbhJu2whyw0ApdUTWpVusQQgd5inLE7fxFHnrUTSGU1TG.M6A7InmF.uu5Y2Vv.
  - name: group91
    password: $6$zVMY7Suz3U1HiLi7$mqayyhS2GdPKdgLLOXZVUd/VnKM7A4rx8EtjzLUegNBHekHM0DwHx8Tz42bz3Lt1qS4g2gDnUFDh3HtP5YaWN.
  - name: group92
    password: $6$4DY5PZd3Kis/RhjI$uDB8BTAomsnXNH6yeGeChvRPz/bGrJt4cd9qjlgyhI7cm0lHZXDMyXGrUTC7Zo2HjyTAPznQiuO/TiPwbAI8Y/
  - name: group93
    password: $6$cG1j667Ap7lFYFEd$y3f7dmC8MdQLY816TOFrK47GMSu1U9xM9j0PROP4QjAGrbPNPHmj4RSL.P9rcRRA94hatjBEKxqNjfQHKx6uG.
  - name: group94
    password: $6$gxeq8jT80OYEB989$8jZq.9U1lWCWibpYBxW1OFw8plqxNzht9zpucWNBpT0BqRe22vM/pdaZvgbN7lDUzOm0OMvuyZ5MZIQtND8Wb/
  - name: group95
    password: $6$lx4kitcBV/0MJm4W$WnX1henyymqItb6Yd7/H7.Nk7jX86xMu7HHl1OdIda50KH3lGuppY5uMdyjQ0uFdqc644vykjGbyt.qeieKwE0
  - name: group96
    password: $6$UsdNOEXCJEXVQhZh$6AI7pRwCL3RRuDkZXpgGQxRBCfvRdCuieP6e6nc3vLCpmnrk6yjSsPnHMXfSjSToZCU3LodpBZyV6V/CnEo5C1
  - name: group97
    password: $6$CSOg.24Ngjyds1bi$hUN2IgAq6qdoZBBXbgw2bt47T1VXwmLY36v3diTDRLdKZtqz5kSb2ELvyu8gQSQtUGOXTaT2G./uingA9yl6L1
  - name: group98
    password: $6$u83v2TOrgTeRWxfB$tGuW61Cz.UsZoVrvDK4ZOpLTt07anv7f4.XcM7TCtZSqKwOmACRi4kslowQsQQt20y7ZMzIhsJ/LHpJ1ICvVG0
  - name: group99
    password: $6$XsciSmrQG.l60/Bm$3l0aVaNYk64rys6h54FQSa7rPnH3cFBq8OXFU5ovIwzfUoc96pAi7i/V1pFSw/EV/azfdGwH23h2e23b6S8jP/
