admins:
  - name: ceccarel
    password: $6$v1sQ32TdgOrrd3$F630Is2SRna0mp.M5iKZmZaYqS42fon8G051LRIrAxCCvfMcrmw9qva2mhHIu5H1Me4xIsOlcSbzNqVwpaRbg.

  - name: andrea
    password: $6$4C/PRuRTFdIm0HIk$DjmJaN/G6iZ3bjsTY1O4TgZIHBtoYbX6AJPZUaEa6Fg71HpqukLEdSiIHFG/Ti1oW2znBAJCeO3EmrkhqzjiG1

groupusers:
  - name: group001
    password: $6$QE2g6ptpMo7sRfnA$thDVAtX2VcfkWF12yWMzhgTs/gXXanH35UcJDnSVHx6eYLjRFql0LKr4LdNLl3N33Uxod/MP5bkzqGTUXMjW11
  - name: group002
    password: $6$ZybpWZGneVH2glZ1$/LBTvIKF7ETVMUwMjVqTfPT7pscgLDdiD1lm1ZOXkMPimqRXYt1OTS4tjzvO0jc.a4F2BtigYYghUUjY4qscW.
  - name: group003
    password: $6$OGtMAOmukNOQhLu/$.5XfZo4lDSsD5..j12tHR05SGbGcV1k4LnR1/6HFGNCCWqgyfT8XwIYTuaZv8OnAbeu/VFzwoTP5CgcqX04BS.
  - name: group004
    password: $6$IBqtUp7C/7ojKxSx$gghFGytmfJPCMU1/zX3gppZ6rOIcar2EMxiVhr4U3W7tDWv/UW6.aL5Q/sNSIa5/1F.dfJhgFo8sSYS8o81J/.
  - name: group005
    password: $6$w9iC6DdXucu1lypp$1QD54sNN9vIL.ZEfh9r2Ej7heyGlpC.64XVbs4iDu1Wcurdi7PRIpCmtoyNJV5DnBsnY.i0HZVYlkBjHrRNHC0
  - name: group006
    password: $6$nt9zd5D5EdB7BHfQ$tD9Y2ujRGSiTqPkzSaq3HwzkEyRyWTrsQwLOzHdDEFWcdyk02pu7s4rvXS3hiXjBuiFhWhzW6De1Y.zy8ZmgC.
  - name: group007
    password: $6$/T8yPkCJn0kso8uq$yJf1fNx3JpG9DGIPYeiCeohvGWYkht65n/iEh3cUmaLVFOEKubbJ9X5NwYIx8K4DcRqz7XZ.A6/4u3lpjlHNc/
  - name: group008
    password: $6$ZfNbR7qEyQlf2quh$SZK1JkMmJ56sA97bQTFHoqPWCGALwqw7v2gKyIdIhHZjD60ocmigPTzkSKXnqjUiLcVcae2nxRy.fy6hlJkk61
  - name: group009
    password: $6$sOHXqgb3I6MB721a$9LjynXbmgI7L0D2zfkqEzqQYyYZBTCxo73mxC0O3PulJM.vw8mxXEySmYHJ4ZTzBGpZ13.Q.6dfSBYCKoK3FX.
  - name: group010
    password: $6$Yy30ej1M6h/ZlAP8$BDtDRX0zPbhoNyKq0yDwtztL.HuRqPs4EroiQLze2o8MPlS6KMViQ9hS97PGB5yhIjQ7IC4ntkj1eXQUhgBsi/
  - name: group011
    password: $6$EpEueHNW4eTO33.r$9e5DzMvv5k8kQqOalaVRrjlUruvl6maGO6QS8Hlsf5xobODXWqgD72wU4PLgzoYiWjyAHv3rY2gfKJ65oQxFC1
  - name: group012
    password: $6$OoRMXYRqVwAgQogi$/pklnkJJm5HO2P9uWjfw9KDRdAYSwjvz7m13qEgfhtG31CziQhSCQtT3ZZxqS01PqlCyKA5MgzQIhM8Oxvo6Q/
  - name: group013
    password: $6$pQ/QUls5q8AwrFKI$3jw2ldqQf2mDbVYVcmIXGhvsanMVQ5HrwXBpwWGglNhmMrJsA57fQ0hWgZLgaDOqia03KQyT/K3GeIA.N4X7J0
  - name: group014
    password: $6$IPtEYvJ4gFNDCh5a$6KZKOnDaBT.JJuTeJhH4RzMfL7YEVeK89hz8BQYyBRkEmWNdTjN1qGBdYwI.m0XGGp0A2DSkkbKELcyPzfZgn.
  - name: group015
    password: $6$IGQlR1FSmnVbN.MI$nL47oIz0Wl7LZORa/TJv8d2u4biAV2Js8MCDIxKqds3R/0I4zL.n8VnxFg/F1cb6fsezbb..zxxd953UtkAqh0
  - name: group016
    password: $6$cq9MCpV6/lvD/XQB$Hm0xerlTUoe7SBdBvSEhsI5hWkgTrrKP3nifhdXwXmbkWyOiU1JIJh0hxnSvW.A2luBvKHHrfEWL6Ne07wVxy/
  - name: group017
    password: $6$ZqeZQVQKi6thMo7j$EblNdzoyrtrT74vcPq/vp40aDQji9YVoE0sySJfDiO859JaxzpPgdI/K3SaVW8qPAE0JtC86xOL9v75Abr4sG.
  - name: group018
    password: $6$L.mmFJZKQ/KR.KnW$X3KJK2Eyk1dy7BwPN6MzBxnsV92bRspsMT9Ftip9TaVPWcj43Q.ji46hvKuJwGHlrppXXl/pnrQox2RcsZGVd.
  - name: group019
    password: $6$nJCCKhJNBHZROwPE$u5eb1WSTBGjA8Gv8PLpidSQuClghB3RPy7rmyCDf8Te9E4kNk6rxvbMcBY9GgLX/i1kNqECVwexYlEbF2Zeox0
  - name: group020
    password: $6$03mYo59Eaxmr8bRX$2gdzXv6CyLYX5Raxkk3sOHbh77cgaJas9hoqpDl1Y1gUMhx1PO1vX.P3cNPlu/tS5yMScQOzbC4pMKxsJ9rmL0
  - name: group021
    password: $6$z6dhxFeH5PM4V3xg$EMhEhrjHFJvvzZZU3vfgjgUZz1UGiTp4cxfViNmaDrnA6UU2LLnmYvObQ/NDC3jYp.BwFjImHAchn08enyzM/0
  - name: group022
    password: $6$A2pbnwTbtn2s6JsX$EkVoKameiDI.95WzqsVr2Iib3i7uKdr/FURUXUpGmlqBpXgDikmympLWF.Ruq/3pbEfvrPvPgym7r1wO4gpxS1
  - name: group023
    password: $6$d9jCNBSHyYeNMLUC$gxoPPE6Eu1JyJlMGm/mbnKBDveGdJNE5OJDF6rSr6GtSLiD3HLp7SmRDl29debv4aT1/Dm21dGSlTEOANTaIr.
  - name: group024
    password: $6$w8Phuv4s5iczH9Hd$G/Twr1ubCvQEF/INnjvHlnn94b2GwyXUeLqTLf7ndHXQEwWqRKl6WLNSKeOxH/iv8Fqxb1eyB4rc1z1UgVFdN0
  - name: group025
    password: $6$BJyAaQDlpEx7FDzc$rRvYpObOqXux9nKxnO2b3rrJXEWsLVSr6cShiOGhlx1uhrGIU4Jt.nuiDcjlfgaqC5W668OPW/ws7KdEeAD7y.
  - name: group026
    password: $6$vldFK.JRNqZOEqXj$lwgeL58VpwH55CZHuSWWC7kGuYeROj74JAymrUErt8/GB2DgExLJGrQ7D3h/D/6AyT7osGUotNFi.rk2YDLoB0
  - name: group027
    password: $6$yVKBz61FNRDP8y7p$x8XLs/Qej0aCxkOI0GSFAr0ZAiewbRqiSE5SeBUYZFd0qOIDrqQp334aTETi9iRm7iSYbG/7coPX5vZucayxH1
  - name: group028
    password: $6$8bSZJYr2gVI.lzZ2$Ya94p2BdAKcspLk4LTjaDLBEUVJ4ciuGuCH2bPPyjSX4azGhDyO4PFU1YVpkbNuqfeqahVLAJX3q7WdUfwtC10
  - name: group029
    password: $6$Eu/AV90s1/8g.MP5$g/4U9wcVV3iRaJVInyEfufP0LfIdDqYROB.M8xfCTAowVVROOhjLUthqlBAnn/tE0EYhVQvvQrz8ZcvfrDYPc/
  - name: group030
    password: $6$O2K50Gy5vC00kmDp$/7p2.Bpg5kjblsH8IfTrZPcCsAtsfcOi4mSF0TdQ/WNHvURQOYy.096uLFhkYyak9I21axm0jB.JE/Ufi6MZ90
  - name: group031
    password: $6$KB5jQCzVHxa0rqdO$TaLe2s6/WrYZ3AKqFUsPfY35ifPCMamCHdl3pn8GOvfa74Loh5txlPC90eS1WFHTYed/wGQxw8/SicW0Q5XSQ.
  - name: group032
    password: $6$Ox1FqDBy75fS8HCm$jgn9QSjF.qsfPQ50zLqXxjR5SOYz7fTR/FOYXXDq.Ogc0p9QE5RAQBZHrD8NPMnMecqQSbJT2nlikcW.fwBDR1
  - name: group033
    password: $6$Zga002H3eJsAOVXu$23w6yQGA5pA37fLItdQa1kkw0MTV7TBlYnpxUuRGLqZXmhr3yz7wmDkk66IHP0IjPOEdz7QGoLjmbgJ8QOtew0
  - name: group034
    password: $6$K0MH5m3AVxJErJr9$SObSvLqUZpcg4/D4x9C5wtFljwSDo7Jy1maGVGR6D1rqB2q7pxkVoFe7tvejxWa2n80uEg0nbuHWav4eeYkNx0
  - name: group035
    password: $6$vgnzzK5UCEOnCfPO$m424By6D6Sngoxb6o49rZrfHq1Sx3qb53YuGe7tQ5MNOUIZVHj76yMLATaGbKlqPz3Dh3Myfp7qoKiSmGZyct.
  - name: group036
    password: $6$IsTLtbCBCKmt/11l$jHl.ICVcQqEvUDpBK8ia8/dI293wMOgQmUE0OfOroXPTq7KF2CpU45zL1nm4WImeluQe6ffZUJZ.V4PFr73I3/
  - name: group037
    password: $6$3Xo3BGuV4bg6eZlD$Qsh9eFSr34dFHbr/0IpmhZFU28gws2QNorVkbhzUNQXI5V8eHWlwzq614vo/h17csXiuqBmWx54apWW2qtdjj.
  - name: group038
    password: $6$dSPgYCIjfxX13bDC$oiMBHg/r1QUVHJ1JMuZQwHLLj48K43VNgDWFJOWE8S7dwsh0vK0DVcYBvlNnFyjm3OfyrWb4QYtH8gPq70bNR0
  - name: group039
    password: $6$1rrt77qNLVq3.Ex4$mnOKlsLVXlXVL8M1Y6RpXf3aNcvWx4kc5MmgSkjiSViitzX1dhVc0JnljPkQEaKkilgrEHvS7vBimw.f7eUVp0
  - name: group040
    password: $6$2V0TMEOzTUBqagrR$hwCvKhXVHLn/9su8XXU.CFUvBEXC26f9b/54sTyq8zM6oY2I79gMOhgSx6GFOzxO7uSKchPflu7fdTxdntAif0
  - name: group041
    password: $6$QzDF841319VLAxHG$nxbPX3EFrsdKx8EcMwkbca/pDuTiEH/E0TkMHoQvmCFAEv69mJSaLF/vWZKO/8nL3D6GlFiTyvf40oeYiwhEc0
  - name: group042
    password: $6$FGfiwh5G8Uqev1O/$6xD4LftpO8zDuBJNoZRbAnu4eYluT.6Bl.a6oSaqfy9KNMbSUAk5OudQj.aMIcJlD99s0pkADuI/tFRFhEiOx1
  - name: group043
    password: $6$44uQnVstbtPnyhNi$MKmFgpIAlyG/8P/IOlO6lfJSZg7IzkdEQ/kvla4s1TtZPbKJAw2MKV56UshTDc9abpQjgOXBpQOzwQp67NuWi1
  - name: group044
    password: $6$rnGtNkD09KGSC4PP$6IFndDjZpxlE4XT9I7P3EnHR6uJn2HCNFeni.s3YMKKZEjYxOpqKRF0X9WSk1PZnUpLA6myyGMtn.IyPBAhtr0
  - name: group045
    password: $6$dRt5sfPJ9mqyyUH4$lDNNNR2tJt5wIMlFa1PIVQ/FAaZsniXmZdrmhk3B6xcxoFv4ax75SkO3RLfRFmMl0Sl65zxYCw3VQpbk8Stk2.
  - name: group046
    password: $6$7PiwwiyUqoL2ARAy$kW3EoIQS93FDbuvUr9Wo/3vzIVV3vgvosYakK615LVLQ7xK9h0EnbZtVLbD6d1L9XF1dB/LdMcJk3FUlzsHgs0
  - name: group047
    password: $6$GYFmN08xAdtCjt8P$nXu/QSoW5gvbN8KG48xfxQcoIuglQtJwFHMpF9A3fexaY598QezI5g6jR8LRlBa37fjXAya9YLHZj9/mrFv6s.
  - name: group048
    password: $6$P.qp1JiBjyB35oYw$pukAbwCVE0EU2wzN3p30osLTbKLNVd30vhTXv4qJnjUyt2RSvH2yc6O0gBIzeWTsHJ.FxNcRUq8Gfzc2Krave/
  - name: group049
    password: $6$uAkcywl4S7gjs5vm$ygAG2p.811Xo2MBz.babGINPZRw4XFPFBtfM/owr84cfXfKi3FEzsinqSn6lNqJwSfFK2n3DttsbQ3/CwG07h/
  - name: group050
    password: $6$iGuHMp2FmncDfUKS$Kp9qWWJHoY6XDh/FmqGeZFCxr4YB4kKCehvt3Z1L2s875yC6YEYy9UOsdE2ZzhCcxmYihXwjs2CEUPZS.XTeE/
  - name: group051
    password: $6$Yy0/HbInKWc2arMi$TxaYujWnZW5XgcZKFrPqt4douRvn6xy7TPglikieD.Z/2iSx/CcgPtBDA7YOuSBMO7BM5eiGOW2iT5NzGBj2G0
  - name: group052
    password: $6$zIUr2wtgM951lagQ$Ke6dMoxNZyCuU8xnSvTM5gUpBvNb3Z7r.iIh2Xg7cxPDnTqFUNWMeUoBE6zqmXmudwULUP.79ueVl5o.KsI39/
  - name: group053
    password: $6$TiUEaz7Y3f7az4k3$rTk12bIvRx9NKuT.DiUqMWuMQfC4Cgk89pzUGUoIw3FdUpPIGv3ZZXVr2JOW60BYbEdRXvadXbpSjGyXB.X.//
  - name: group054
    password: $6$QJm2l9eJHPwSP7jn$XVKC1PfJV7MpVufW1Ozpozq2cKnX1rsJntMp8NVhbq3F9JgFsoORGUmR0ZjXogPy98URBQgnBpam4IS5DFrL2.
  - name: group055
    password: $6$bRW8SXihaoIUdMUC$6gu6iXHF2W8URcnzka2kL3Q2hv5IPyjzNbPn3lqo03L8e36PTf5mJGgXEjy3aWMQPYQo.JItvYB0sE.R4eNz90
  - name: group056
    password: $6$2PgTJ95FtoIXrDoc$Co.7cCk6sb.OuTb68PDKJlIQdtnxkmMtShuHoLfWNheCf34lWzpYPcCy3lIIvG8j6dFy8P1jNE6tt4mtTupSW.
  - name: group057
    password: $6$3/2D3B3uAT976Jtj$H6QxiTDDZLh5K87ZlhCh36h3JdUBrOnWtXd0fvfC1KH0rDFRKhGMb8V1057kzIrqasp7FuAzvRD5xBIsODiUx1
  - name: group058
    password: $6$Z2Frm3EKy.dzYwJI$XuqEkrgZk/q53.EGjkvy1ZtU1pi8M/FdmYigcIPe6xsJ2lDGrrfp7LqH4o3JmEdNTrPo49BOajA3k5WTl4hT10
  - name: group059
    password: $6$HjRaC39k0Y.6X/gi$Xx.l1hmGe.Ylokmq5iwAw57SXlJLG/gO/2WbRdwhcGYrXMlJFU61yMBSk5OBr3Ngu/h4QX961bVGdY/D8bO1D.
  - name: group060
    password: $6$Wk2UNL2UPjRoA0uM$GH6rE36de3vTF7SArywxpDjDa2EbgSJRocKhZECxOEf7EMl1UfGdW.ZmCLQRoFwMwgY9VdVBA4FAwKYVg6JeH0
  - name: group061
    password: $6$LZ0SoPNocFY9tHBZ$7CmkicE0O6N0EAN3.0THvb8ttCMknkC2NIEFnB1hR1lD/WLZQHsOy3uC5/fC/eSjN6lwxteG1ZzNjOqW6CvqD.
  - name: group062
    password: $6$soJULf.8lh0/BItI$8aK4PoeuBSGOMEpurHz2gnUBugslV5CxIsesZzXOSu8uekq3hmAsA0XQUhO13OLKaWIv4tjFaFdFBX6Jb75mY0
  - name: group063
    password: $6$kHT2/zd7QOxJ0Cjo$DnubyuaxskuCm9h4JUIF9BpQ3uJBj/f8dF3fXvsdUthIqWY5YIzNcbzy1I8To4gCkChAUj9CK6DplrvCFfJnz0
  - name: group064
    password: $6$meWGLhQuBL3KmlbQ$38OYpxMamKlxnr/4P9ZhOo7NFgrPnYMnSpN.mDacto7KgaUAPqMd4mREzDSdpZ2OBC9.GgL7ksrETO7f2r.i90
  - name: group065
    password: $6$0t1I7M2CPDVpmOY.$Ne8ns1n/E.QxSuVXSUW6Xk.LuaxsCW4O0Y9DeCimJJiUDAY3vKKx3W93I6Up6YGS4FcVY7B62eVnatat6ze1V0
  - name: group066
    password: $6$FZeMzuu.pjeIF8/w$/MMtVwwOnaBHT9g15O1Ko2iVUobMD1p2rRqNqYEVNiFhJwTtD6xYwTtttmv7Lzg.vHHqo3dIJ4V3uFcg2p4Je/
  - name: group067
    password: $6$t/4f6gYU9KbmzIJt$aJy0ApJ6Mz8ATvY7GJTuqi1oq0Jcr66TH/SYC3binXkq5JgcXGASWfkuATXv8sY9tCRvAQ4OtWeul3hteUZv/0
  - name: group068
    password: $6$RtIVSIIi5MmZB1cb$qh/pMkRg8Dc6qE3rDhzR.seoKlgDG8ajg2eKRKYvNhsf/WWFvKOcKUlsAKVVjmH0af9lVqBLXMB5wc0gioi.51
  - name: group069
    password: $6$wTqQpseR/48l7VBH$KhJ5eIbGoFzNxZi0M.Bq3rqKemjMx86Jn0Fb/gaKq0QbBHHNyAT3im4jXL.l4i.5nuHc/u6JLUOfhwRF73EL01
  - name: group070
    password: $6$Gi24gAyRO7O1meos$t7JrwETOlsYgQBVfJOWUKE9HHINekMKIFLUJO1.CjwYYUhc0S5.t4yZfL4ptnZPDb86LORtE/d6K8QcJ5dQJv.
  - name: group071
    password: $6$HVG2BR4zmM9Z5BLW$0STGRWkZi6wBDWHnWm7gv82XpQAV1YO1xrUX3wAEZlMgSmIbVlUMtJXJwgvq7LU1rNb8369c4Q5ZKkuJezbji.
  - name: group072
    password: $6$8s33uy7HtkO.IjTf$8XusBDFUFw0jwptxp0HRBq0l1oOKRtddaAVvKlW9kqrt6uTOlwQG622H4s7zuzR1aRzwap6C7CZVESHpkgG7p0
  - name: group073
    password: $6$f2tkifZUxpUF4N4g$csX3spKaqlDKGedMr6FFQwTDbOJpoqI3j8TDncTO2VSLEpM3wwklpwIC.QAlkAbrz0oVCDZcWaPT1CKP77qW./
  - name: group074
    password: $6$Z3bQvQAXQEMck/RT$xJnt0eOcyD.C5opsy45s6Ap9/z4Uwhkb.keMDDZqm1CQlUMQ9KG/mxhH6clrtsBN7KSKioNU.fY/MSjT1uND81
  - name: group075
    password: $6$d1iVhKe31kk2SuBw$dkEc12bU3Rw2G2XLJOPTHZJCDEFPpV9p91sBPiYMAGN.ZWYpxyB6fGYiSEe1CK4oRm.DYFYN3boFZImxRbcUh0
  - name: group076
    password: $6$/8wlmZgb.uYebmEr$Uf7iJrotfdAdRxI9FX5WnCJf8Yk3StBMh2ALHAaOE0D2RvGSyzguApW8JYd7G70CoWB43ZyWcsk/mg61VKzBp0
  - name: group077
    password: $6$eNDOAa0rUHDIQLh9$9DCwA7pBW0DRlbYnqKPRB3iQqvL/juRxtkMHmcfRoAa80QqTMAA8oItOkTjoHCvJALjPIQo9njKZtNzgpCzdv0
  - name: group078
    password: $6$QgQh1OMJxMHUZ80D$7t1r.zF0u1W57aQMBCFuDWTFEvnDP1G0ORmWyH2xKn/RsO7QsprkQdmbQg2uon1FI7KZGj5OfTCiWEhyC.qnE/
  - name: group079
    password: $6$L3jB21CQttV.Zlva$je59VdzYWXkCWFjx8h.GXBvzBnxG3.PcEzyBqbZE8NNKYBiZtjvc.MFCNln.lCKHWYHqwGudALROAD1GjM3E.1
  - name: group080
    password: $6$dkUVF/XB6jg2eAUR$dA5afeOWAuitFs9ZCff.SQKu.KbNFK0FA2yeJ.9qU0bjGsUoVgGwCYDtBUN/bHq6JERW3QrV45dCdZQkznMnU/
  - name: group081
    password: $6$bM4DxGVzSNQfrHWW$pIsX2HtbfymeI/MOckj5ccxrFH8LUgaJ7ijDQLSVEudnJ3YhBj7FfbK2Lon8L8WtVRbZRqX0QTFIQgQp/UJWY/
  - name: group082
    password: $6$o06TA8n4OcAn7rLO$CmeJhgjHKM2yFQqcIgKnFpouFeAKBPkqx4pDmesHbiWeqWdbxS3M.ZxSjmSx.MjNIfnS3A2su4RTVOrikIVID1
  - name: group083
    password: $6$9ug9ZSnb3sXAWEfb$n04VU5p2KIcEJSOEtWPUi5gjNwX1nrcF4.zvod0nwdivY1XFLuNpQ4MR0wV5IbQjJlzcN5jRKHYWoFauwSU5J.
  - name: group084
    password: $6$npR1vu2F84WQny2q$LYCunIL6hrhiy8s2C/mTzGuG4rHn7r/XhpES71iNrNIj5Xbqyvn8Or0UtdJw6.pnfAKQnTrC3VJOYFJYDaE/71
  - name: group085
    password: $6$uzvx3PhQszXJYF.r$TAczhjeMeRVitSlVZAoG4IZVZjouVsRfm4HFMH2KkuF9fpSy.c0/KQ0a38tNJCoZIKJy.i47BR/Us/h2M.HxW0
  - name: group086
    password: $6$.JGqYbgF1Xnn1XMR$gvbFkIAg0PiHnLg6GvXjghHm8kPC.ip5VvPEpBgAl.lCBRKRga7vq9nJe53EUD.oMRVZRZPFVXnjF5IcuIV1w1
  - name: group087
    password: $6$WFUmSsmj.fezGgui$0.ByCc6/VteuUK1fgnytRA9qiQ1RSeLs5v0v9z.CTvDPcuAHZGaAzy78J6EjmlwwLhTQlEKFIGMhZnurBA6if1
  - name: group088
    password: $6$DnP8iC5FVDDCvQy5$EhQSXiq1UMUd4TDe02QvMqUEmN3l2P.UijIv20X20urLdx1MXdFiH9JbTbu9Uxvk7k2I0oi7wx5VGt4Q2HbFU/
  - name: group089
    password: $6$r1zeY7areHjd75er$TX2nmf4btlWHngFApa7Ny5hnbZWuT/rAx1gUfRXMvCsfXKhtZhBnNde0sbrVu9egLnlnG.7133ZbITqlg6qcE/
  - name: group090
    password: $6$i6L1VI2o8qWBo7Vr$XHLYgocZV/lb6NJ9bbEtqzylznu8LHZ5r.fz8dRtUNknc8ptwR4t8hW1KGWxC3DzeUvlvkZMzBRO73IZUm9O81
  - name: group091
    password: $6$FrJ6.SBbJy/EsWZ6$TIU.QHvkPRESBq1iF8ovbRZNh8xY65TVcQmv6zh5Gqj1ow6D2mEqjDeUVVjEBqikeP.HhdKC7CxZSq12ARlAf0
  - name: group092
    password: $6$HbPG5ltb2tAOez32$xW50CMS5w4.qQiIfkk0j7klLCPdyL8TOie5otmRx1DK2SYgS9pQJqMqC6ADJDjU8jH6hdJvzSWnjAaWnqDKCc/
  - name: group093
    password: $6$0vFPN0ScWv7YndIQ$G.j7mc0WNsAaf742TKI3y9dlhD7paDHo1SiFB5eHHbQl33AtPb0T5KPoINhK1hW6/7aU/qdYh7AJOGxLxQTdA1
  - name: group094
    password: $6$2Equ3fK.aKeKhfVZ$mvDbaxyu3wUaKoSsdkqL/QnVjnkUr.1KWdMTap4VdWceM1mphWjEjnPvfqI18uB2LULzNyvU/5VXDIKnAaS.u.
  - name: group095
    password: $6$3EtmKyQ/ICcw.mrh$k9BNEK329eWvur0qRkZok1pP0qtb4gHt/lQCftmw0TjILGv8.qrWYo1y4imgGfin/L8f5I7zqKccHFGhaV3xn/
  - name: group096
    password: $6$qPCRA4aGN4eJb.ts$V20nQ5JiSK7gbT8ruXgrIz0C3fLuhqK7wpDbrzk2UaBO9S7gLZ4/nLw4vmpPzieHOAo4qBYkk2PWkfXxXDCNy1
  - name: group097
    password: $6$PEdFexCFsb62HIlx$Cm2oiJhj3Mt5bH6BxOJBNhaCWLo3nPnO7vmipkQm4jdVU1U7tzZ3LMhTTV2VbnHaYwPb1WeXYNr1ql6Y2Rjv71
  - name: group098
    password: $6$NjXNOloou5EC18VJ$ITCbhm/P7eVs/1QXKeT8Y2uVGD9UEBZVKecnk95tUE1vHuqZ4g8VgivzyOKgyLyf2O6MbnAImePET31CtLtBn.
  - name: group099
    password: $6$ULepO2OPB51MXC7U$bIvTDnGSvb8HIjmovrV2/EiKA/aNZy7XP5k8XR6hJbxau8x1bsf1IjRjdsqf/azzI1uq/0T5R3qZxu7ZPBnSj1
