---
- hosts: frontend
  
  tasks:

    - name: ensure that sshd allows password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: 'PasswordAuthentication yes'

    - name: include usernames
      include_vars:
        file: usernames.yml

    - name: create group for students
      group:
        name: students
        state: present

    - name: create student users
      user:
        name: "{{ item.name }}"      
        password: "{{ item.password }}"      
        update_password: on_create
        state: present
        group: students
        groups: hadoop,spark
        shell: /bin/bash
      with_items: "{{ groupusers }}"

    - name: configure bash
      copy:
        src: files/bashrc
        dest: "/home/{{ item.name }}/.bashrc"
      with_items: "{{ groupusers }}"

    - name: create user directories under hdfs
      command: "/opt/hadoop/bin/hdfs dfs -mkdir -p /user/{{ item.name }}"
      become: yes
      become_user: hadoop
      with_items: "{{ groupusers }}"      

    - name: change ownership of user directories
      command: "/opt/hadoop/bin/hdfs dfs -chown -R {{ item.name }}:{{ item.name }} /user/{{ item.name }}"
      become: yes
      become_user: hadoop
      with_items: "{{ groupusers }}"

    - name: set space quotas for user directories
      command: "/opt/hadoop/bin/hdfs dfsadmin -setSpaceQuota 1m /user/{{ item.name }}"
      become: yes
      become_user: hadoop
      with_items: "{{ groupusers }}"
      
    - name: create a data directory
      command: "/opt/hadoop/bin/hdfs dfs -mkdir -p /data"
      become: yes
      become_user: hadoop

    - name: change ownership of user directories
      command: "/opt/hadoop/bin/hdfs dfs -chown -R hadoop:students /data"
      become: yes
      become_user: hadoop

    - name: make data directory readable by all students
      command: /opt/hadoop/bin/hdfs dfs -chmod -R g-w /data
      become: yes
      become_user: hadoop
